### ISSUE TITLE
Image refresh for debian-stable

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/bots#1125]
Image refresh for debian-stable
 * [ ] FAIL: image-refresh debian-stable

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-1125-20200804-234747/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1125-20200804-234747/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1125-20200804-234747/

**Comment by marusak** [comment]
```
+ mv /etc/network/interfaces.d/50-cloud-init.cfg /etc/network/interfaces.d/50-cloud-init
mv: cannot stat '/etc/network/interfaces.d/50-cloud-init.cfg': No such file or directory
```
