### ISSUE TITLE
Failed rebases don't stop the tests

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#1386]
https://logs.cockpit-project.org/logs/pull-14688-20201111-134313-cda96e1d-centos-8-stream/log.html

```
https://logs.cockpit-project.org/logs/pull-14688-20201111-134313-cda96e1d-centos-8-stream/log.html
Running on: `2-cockpit-7`
Command: `PRIORITY=0005 ./make-checkout --verbose --repo=cockpit-project/cockpit --rebase=master pull/14688/head && cd make-checkout-workdir && TEST_OS=centos-8-stream COCKPIT_BOTS_REF=master ../tests-invoke --pull-number 14688 --revision cda96e1dd80580728e8bbd0ad4d09d8677416cda --repo cockpit-project/cockpit`
Cloning into 'make-checkout-workdir'...
From https://github.com/cockpit-project/cockpit
 * branch                refs/pull/14688/head -> FETCH_HEAD
HEAD is now at cda96e1dd shell: Allow editing hosts without admin privs
From https://github.com/cockpit-project/cockpit
 * branch                master     -> FETCH_HEAD
Rebasing (1/2)
error: could not apply 2c9f7b929... shell, login: Overhaul SSH host key handling
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 2c9f7b929... shell, login: Overhaul SSH host key handling
+ git clone https://github.com/cockpit-project/cockpit make-checkout-workdir
+ git fetch origin pull/14688/head
+ git checkout --detach FETCH_HEAD
+ git fetch origin master
+ git rev-parse origin/master
> ea431ed9162c4b7e894dcf705f56ac036c0bf4b2

Rebasing onto origin/master (ea431ed9162c4b7e894dcf705f56ac036c0bf4b2) ...
+ git rebase origin/master
info: Could not add alternate for '/home/user/.cache/cockpit-project/bots': path '/home/user/.cache/cockpit-project/bots' does not exist
checked out bots/ ref 40d4a2db32e47e38a1b6e7b3879716d73d508019
++ dirname ../autogen.sh
+ srcdir=..
+ test -z ..
+ PKG_NAME=Cockpit
...
```

This later failed like this:

```
Parse error at dist/static/login.js:547,0
<<<<<<< HEAD
^
ERROR: Unexpected token: operator <<
```

**Comment by martinpitt** [comment]
That happened in commit 1d393455ab0, which made the git commands non-fatal on error. @marusak, do you still remember why? If not, let's just make them fatal again, and then *if* something legitimately fails, add more specific conditions with comments, or try to avoid it in the first place?

**Comment by martinpitt** [comment]
Sorry, I was wrong -- it was non-fatal before as well. It just used to be a tad more atomic -- now `rebase` would run despite `fetch` failing, for example.

**Comment by marusak** [comment]
> If not, let's just make them fatal again, and then if something legitimately fails, add more specific conditions with comments, or try to avoid it in the first place?
it was non-fatal before as well. It just used to be a tad more atomic -- now rebase would run despite fetch failing, for example.

Yeah, there was no change about accepting failed rebases - that does not make sense of course.

I thought it would fail if rebase failed. Lets just do that. It would be nice if we could get specific status about that to github, but if it will be just obvious in logs what has happened, then I am happy as well.
