### ISSUE TITLE
image-download in separate containers on shared cache directory is failing

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/bots#1473]
In #1472 I made a change and triggered a refresh.  The refresh happened to run on the centos cluster, and the image was available there.  I cherry-picked the refresh commit into the PR and pushed again, then triggered the entire testmap for `image:fedora-32`.

That results in an awful lot of tests spinning up on various containers on the cockpit cluster, all of which are going to start the large download from the centos cluster.  Some of these containers ended up on the same host, sharing cache directories and out of those, some tests failed like this:

```
 > https://images-frontdoor.apps.ocp.ci.centos.org/
 x https://images-cockpit.apps.ci.centos.org/
 x https://cockpit-11.e2e.bos.redhat.com:8493
 x https://10.29.163.169:8493/


=> https://images-frontdoor.apps.ocp.ci.centos.org/fedora-32-9a4530a00b40f734b97cce0dcbfa399b1e2153d9a6103c2e76c540d4c52b23c3.qcow2 is the fastest store
image-download: [Errno 2] No such file or directory: '/cache/images/fedora-32-9a4530a00b40f734b97cce0dcbfa399b1e2153d9a6103c2e76c540d4c52b23c3.qcow2.https:__images-frontdoor.apps.ocp.ci.centos.org_.partial'
image-prepare: unable to download all necessary images
Test run finished, return code: 1
```

For each host where there was a failing container (1-, 4- and 9-cockpit), there was a passing test in a different container on that same host.

That sounds a lot like image-download falling over itself.  Probably we need to up our locking game, or do some other approach.

**Comment by martinpitt** [comment]
I often noticed that as well after image refreshes. I checked the containers, the images were there and that after a retry everything worked. Thanks a lot for finding the root cause of this!

**Comment by martinpitt** [comment]
Happens on [e2e](https://logs.cockpit-project.org/logs/pull-15812-20210614-194001-d998acb9-fedora-33-firefox/log.html) as well.

**Comment by martinpitt** [comment]
Possible idea: Create the lock file in the same dir as the image cache, so that it works across multiple containers. According to flock(2), this is also supported on NFS (for CentOS CI's cache dir).

**Comment by martinpitt** [comment]
This could be as simple as

```diff
--- image-download
+++ image-download
@@ -248,8 +248,7 @@ def committed_target(image):
 
 
 def wait_lock(target):
-    lockfile = os.path.join(tempfile.gettempdir(), ".cockpit-test-resources", os.path.basename(target) + ".lock")
-    os.makedirs(os.path.dirname(lockfile), exist_ok=True)
+    lockfile = os.path.join(os.path.dirname(target), ".lock." + os.path.basename(target))
 
     # we need to keep the lock fd open throughout the entire runtime, so remember it in a global-scoped variable
     wait_lock.f = open(lockfile, "w")
```

The main drawback is that this keeps the .lock files in the cache dir forever. They are hidden (hence the careful naming), but a bit of a wart. Some ideas:
 * Use the .partial files as lock files, and make sure to always create them. Ensure that image-download re-checks for the target file after acquiring the lock, to ensure transactionality.
 * Remove the .lock file after renaming .partial to final name. Again, ensure to re-check for target file after acquiring lock.

**Comment by martinpitt** [comment]
I can reproduce the crash:
```sh
mkdir -m 777 /tmp/cache
chmod a+w images
podman run -it --rm -v /tmp/cache:/cache/images -v .:/bots -w /bots quay.io/cockpit/tasks ./image-download cirros
# run that twice in two shells in parallel
```

with some luck, and re-raising the suppressed exceptions, one of them fails like on the bots:
```
Traceback (most recent call last):
  File "/bots/./image-download", line 323, in <module>
    sys.exit(main())
  File "/bots/./image-download", line 316, in main
    if not download_images(args.image, args.force, args.quiet, args.state, args.store):
  File "/bots/./image-download", line 298, in download_images
    download(target, force, state, quiet, store)
  File "/bots/./image-download", line 198, in download
    os.chmod(temp, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)
FileNotFoundError: [Errno 2] No such file or directory: '/cache/images/cirros-ff4ccf16a162d7d3bf86d30141bd8cfe30821dd3b09712fe2f84d201c8e948af.qcow2.partial'
```

That also demonstrates that bots download the same image multiple times in parallel.

Using the `.partial` files as lockfiles is really awkward, as that would force to run much of the code in reverse order, and introduce race conditions in its own right. Cleaning up the lock files works better.

I sent a PR in #2118.
