### ISSUE TITLE
Image refresh for fedora-29

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/bots#15]
Image refresh for fedora-29
 * [ ] FAIL: image-refresh fedora-29

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-15-20190920-150202/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-15-20190920-150202/

**Comment by cockpituous** [comment]
Command '('git', 'add', '--', 'bots/images')' returned non-zero exit status 128.: https://209.132.184.41:8493/logs/image-refresh-15-20190920-150202/
