### ISSUE TITLE
Image refresh for rhel-8-4 (Experimenting in #1551)

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#1562]
* [ ] FAIL: image-refresh rhel-8-4

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-1562-20210120-112323/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1562-20210120-112323/

**Comment by marusak** [comment]
Ok, I built it locally and it is still broken the same way. So no need for this anymore, I was just lazy and wanted CI to do the work for me :)
