### ISSUE TITLE
Image refresh for rhel-atomic

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/bots#180]
Image refresh for rhel-atomic
 * [ ] FAIL: image-refresh rhel-atomic

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-180-20191027-051414/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-180-20191027-051515/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-180-20191027-051414/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-180-20191027-051515/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-180-20191101-124646/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-180-20191101-124646/

**Comment by marusak** [comment]
Indeed, I could not find any usable image anywhere. Lets give it a few days, hopefully it reappears, if not, then we should report this.

**Comment by martinpitt** [comment]
This still doesn't exist. I asked on aos-devel@

**Comment by martinpitt** [comment]
Should be back now.

**Comment by cockpituous** [comment]
image-refresh in progress on 11-ip-10-29-163-166.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-180-20191122-165757/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-180-20191122-165757/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-180-20191122-170606/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-180-20191122-170606/

**Comment by martinpitt** [comment]
The image got downloaded now, but it fails in a weird way afterwards. I may have broken the subscription stuff somehow, I need to look at that.

**Comment by martinpitt** [comment]
Fixed in PR #278
