### ISSUE TITLE
images with hostname "localhost" try to set an invalid hostname

### ISSUE THREAD

**Issue by ptoscano** [cockpit-project/bots#1908]
While debugging with @martinpitt the issue with subscription-manager tests with RHEL 8.4 (#1711), I noticed this in the logs:
```
Apr 05 22:15:20 localhost NetworkManager[868]: <warn>  [1617675320.8611] hostname: couldn't set the system hostname to 'rhel-8-4-127.0.0.2\0582201' using hostnamed: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Invalid hostname 'rhel-8-4-127.0.0.2\0582201'
Apr 05 22:15:20 localhost NetworkManager[868]: <warn>  [1617675320.8612] policy: set-hostname: couldn't set the system hostname to 'rhel-8-4-127.0.0.2\0582201': (1) Operation not permitted
Apr 05 22:15:20 localhost NetworkManager[868]: <warn>  [1617675320.8629] policy: set-hostname: you should use hostnamed when systemd hardening is in effect!
```
(from https://logs.cockpit-project.org/logs/pull-2557-20210408-110040-fee291b6-rhel-8-4/log.html )

Indeed `rhel-8-4-127.0.0.2\0582201` is not a valid hostname.

**Comment by martinpitt** [comment]
Sorry for slipping this for so long.. 

I just ran subscription-manager's tests on `TEST_OS=rhel-8-4`, and indeed I still get this. A bit more complete log:
```
NetworkManager[864]: <info>  [1625205315.2218] policy: set-hostname: current hostname was changed outside NetworkManager: 'localhost'
NetworkManager[864]: <info>  [1625205315.2219] policy: set-hostname: set hostname to 'rhel-8-4-127.0.0.2\0582201' (from DHCPv4)
NetworkManager[864]: <warn>  [1625205315.2235] hostname: couldn't set the system hostname to 'rhel-8-4-127.0.0.2\0582201' using hostnamed: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Invalid hostname 'rhel-8-4-127.0.0.2\0582201'
NetworkManager[864]: <warn>  [1625205315.2235] policy: set-hostname: couldn't set the system hostname to 'rhel-8-4-127.0.0.2\0582201': (1) Operation not permitted
NetworkManager[864]: <warn>  [1625205315.2235] policy: set-hostname: you should use hostnamed when systemd hardening is in effect!
```
This isn't specific to sub-man, a mere `./vm-run rhel-8-4` (or -8-5 or -9-0) in bots on the pristine image does that as well.

Interestingly this does not happen on our Fedora images. It seems the difference is that /etc/hostname is "fedora" on them,  while on the RHEL images it is "localhost". Seems NetworkManager has a policy to use the DHCP provided name for "localhost", as it considers that "not sufficiently specified"? If I run `hostnamectl set-hostname rhel` and reboot, that issue goes away.

I'm afraid the DHCP  server is not under our control, that's between libvirt and QEMU. Our libvirt instances are called "rhel-9-0-127.0.0.2-2202", and apparently libvirt somehow turns the second `-` into this `\058` thing (which is apparently the decimal encoding for `:` -- it's not an octal number despite the format, and as hex it would be `X` which doesn't make sense).

**Comment by martinpitt** [comment]
The DHCP server isn't under our control, but the desired host name actually is. I have a local fix (going to send a PR soon) that fixes the `:` in it and replaces it with `-`. Then the message looks like
```
NetworkManager[640]: <info>  [1625207362.3520] policy: set-hostname: set hostname to 'rhel-9-0-127.0.0.2-2201' (from DHCPv4)
```
That doesn't have any actual effect, as /etc/hostname is still set, so the static hostname remains at "localhost". However, it does help after `rm /etc/hostname`:
```
# hostnamectl
   Static hostname: n/a                                                                        
Transient hostname: rhel-9-0-127.0.0.2-2201
```
This may help for some images, and as the fix is easy, let's get it in anyway.
