### ISSUE TITLE
Update naughties for `testlib.Error`, or fix the format

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#214]
PR cockpit-project/cockpit#9571 moves verify tests to Python 3, which changes the error output from `Error: ...` to `testlib.Error:`. tests-policy normalizes that to `Error:`. Either find a clever way to make the exception print out the old format, or change the naughties and normalize into the other direction for Python 2 test runs.

**Comment by martinpitt** [comment]
Doing this now, as I have to unbreak the naughties anyway.

**Comment by mvollmer** [comment]
Fixed by #215
