### ISSUE TITLE
bots: "import task" crashes when not in a recognized GitHub repo

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#23]
Since 718be03cc017995b8b0aa549137168b37fdc7cc5 `import task` will crash when the current directory is not in a git repo with a origin that points to GitHub.

This happens because `import task` will unconditionally run `api = github.GitHub()` and this will now raise an exception when it can't figure out the GitHub repo from the origin remote.

See cockpit-project/cockpit#10554 for a concrete case.

**Comment by marusak** [comment]
I think we can close this. This was back from a day when bots were part of cockpit itself and we were  running unit tests on them. Importing task is pretty much pointless unless you want to interact with git.
