### ISSUE TITLE
bots: Move test maps out of tests-scan into the projects

### ISSUE THREAD

**Issue by atodorov** [cockpit-project/bots#25]
Now that we have other repositories using `bots/` and depending on Cockpit CI infra, namely lorax, I think it makes sense to try and read the context from a file inside the current repository, not hard-code it in `bots/tests-scan`.

Shouldn't be too hard to implement, let me know what you think ?

**Comment by marusak** [comment]
The general idea still stands but we are not going to do this in no near future. We would need to change the general approach how our CI works and also how end users use it. Testmap seems to be working fine. Also it makes it possible for us to have overview of what people use and how they use it - so for example if we want to remove old OS we know, if someone still uses it or when introducing a new one we can hint projects to start testing on it as well.
