### ISSUE TITLE
Image refresh for fedora-rawhide-boot

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#2947]
Image refresh for fedora-rawhide-boot
 * [ ] FAIL: image-refresh fedora-rawhide-boot

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-2947-20220216-125151/

**Comment by martinpitt** [comment]
I fixed the cockpituous token permisisons; unfortunately, for image builds we still need `public_repo`.

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-2947-20220216-125151/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2947-20220216-125252/

**Comment by martinpitt** [comment]
Closing this, this needs fixing image-upload. Please iterate in a PR.
