### ISSUE TITLE
Debian based distro lacks "%wheel ALL=(ALL) ALL" in their "/etc/sudoers"

### ISSUE THREAD

**Issue by yunmingyang** [cockpit-project/bots#3275]
Related with: https://logs.cockpit-project.org/logs/pull-669-20220420-102953-6cf7e5d1-debian-stable/log.html

**Comment by martinpitt** [comment]
`wheel` is a Fedora/RHEL specific group. Debian's and Ubuntu's counterpart is the `sudo` group. I propose to rename `testBasicWheelUser()` to `testBasic{Sudo,Admin}User()` and use the correct group for each operating system.
