### ISSUE TITLE
unable to reach machine via ssh

### ISSUE THREAD

**Issue by yih-redhat** [cockpit-project/bots#3512]
Hi, https://github.com/osbuild/cockpit-composer uses bots to run the automation test, recently I was trying to run the test of cockpit-composer, but I was blocked by this issue. Can someone help to take a look? Thanks.

Problem description:
When I run test on fedora35/fedora36, I always got this error: Unable to reach machine fedora-36-127.0.0.2-2201 via ssh. 

Reproduce steps:
1. Trigger automation test of cockpit-composer project, here is the output:
bots/image-customize -v \
	--resize 20G \
	-i `pwd`/cockpit-composer-*.noarch.rpm \
	-i composer-cli \
	-u /home/cloud-user/workspace/cockpit-composer/test/files:/home/admin \
	-u /home/cloud-user/workspace/cockpit-composer/test/osbuild-mock.repo:/etc/yum.repos.d \
	-s /home/cloud-user/workspace/cockpit-composer/test/vm.install \
	fedora-35
Image resized.
Traceback (most recent call last):
  File "bots/image-customize", line 295, in <module>
    main()
  File "bots/image-customize", line 286, in main
    machine.wait_boot()
  File "/home/cloud-user/workspace/cockpit-composer/bots/machine/machine_core/ssh_connection.py", line 131, in wait_boot
    self.label, self.ssh_address, self.ssh_port))
machine_core.exceptions.Failure: Unable to reach machine fedora-35-127.0.0.2-2201 via ssh: 127.0.0.2:2201

2. Then I checked the libvirt vm status, and the status is paused, I suspect this is the root cause?
```
[cloud-user@yih-edge-rhel86 cockpit-composer]$ virsh list --all
 Id   Name                       State
-----------------------------------------
 1    fedora-35-127.0.0.2-2201   paused
```
3. I tried to trigger automation test on my own laptop(fedora) or on an openstack machine(rhel86), but got the same error.

By the way, is there a slack channel that I can ask questions there?

**Comment by marusak** [comment]
I talked with @yih-redhat on slack and we figured it out. The issue was with `--resize 20G ` and after that the VM not boot due to lack of resources
