### ISSUE TITLE
DBG - ubuntu-stable

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#3831]
* [ ] FAIL: image-refresh ubuntu-stable

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-14.
Log: https://logs.cockpit-project.org/logs/image-refresh-3831-20220906-120202/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3831-20220906-120202/
