### ISSUE TITLE
NPM package fetching/dependency issues breaking Anaconda Web UI tests

### ISSUE THREAD

**Issue by M4rtinK** [cockpit-project/bots#3834]
Since today, Anaconda Web UI tests running in Cockpit CI infra fail with a strange NPM error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/plugin-transform-named-capturing-groups-regex@^7.19.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /work/.npm/_logs/2022-09-06T11_33_04_085Z-debug-0.log
```

Example of one such error:
https://cockpit-logs.us-east-1.linodeobjects.com/pull-4318-20220906-113149-860a5e90-fedora-rawhide-boot/log.html
Affected PR (that does not actually touch Web UI code at al):
https://github.com/rhinstaller/anaconda/pull/4318

We have seen the same failure also on PRs that had the Web UI tests pass on them in the past & have not changed since.
Also, the package build & tests succeed when run locally, hinting on some Cockpit CI infra issue, possibly related to NPM caching ?

**Comment by martinpitt** [comment]
This is usually a corrupted ~/.npm cache. I reset it on all the runners, can you please try again?

**Comment by M4rtinK** [comment]
Re-triggered Web UI tests on https://github.com/rhinstaller/anaconda/pull/4318.

**Comment by mvollmer** [comment]
Seems to be fixed.
