### ISSUE TITLE
s3-streamer crashes with HTTP Error 503: Slow Down

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#3991]
We are currently getting tons of tasks container crashes due to this:
```
   File "/work/bots/./s3-streamer", line 225, in write
     self.append_block(self.pending)
   File "/work/bots/./s3-streamer", line 205, in append_block
     self.destination.write(f'{self.filename}.chunks', json.dumps(chunk_sizes).encode('ascii'))
   File "/work/bots/./s3-streamer", line 97, in write
     with s3.urlopen(self.url(filename), data=data, method='PUT', headers=headers) as _:
   File "/work/bots/lib/s3.py", line 117, in urlopen
     response = urllib.request.urlopen(request, context=host_ssl_context(url.netloc))
   File "/usr/lib64/python3.10/urllib/request.py", line 216, in urlopen
     return opener.open(url, data, timeout)
   File "/usr/lib64/python3.10/urllib/request.py", line 525, in open
     response = meth(req, response)
   File "/usr/lib64/python3.10/urllib/request.py", line 634, in http_response
     response = self.parent.error(
   File "/usr/lib64/python3.10/urllib/request.py", line 563, in error
     return self._call_chain(*args)
   File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
     result = func(*args)
   File "/usr/lib64/python3.10/urllib/request.py", line 643, in http_error_default
     raise HTTPError(req.full_url, code, msg, hdrs, fp)
 urllib.error.HTTPError: HTTP Error 503: Slow Down
ERROR:root:./s3-streamer --repo cockpit-project/cockpit-machines --test-name pull-835-20221021-145814 --github-context centos-8-stream --revision 6bd666705c12a02c8189af45fd4349f89100877d -- /bin/sh -c "PRIORITY=0005 ./make-checkout --verbose --repo=cockpit-project/cockpit-machines --rebase=main 6bd666705c12a02c8189af45fd4349f89100877d && cd make-checkout-workdir && TEST_OS=centos-8-stream BASE_BRANCH=main COCKPIT_BOTS_REF=main ../tests-invoke --pull-number 835 --revision 6bd666705c12a02c8189af45fd4349f89100877d --repo cockpit-project/cockpit-machines" failed with exit code 1
```

@allisonkarlitskaya does this ring a bell? Are we hitting some quota?

**Comment by allisonkarlitskaya** [comment]
@gundersanne mentioned something like this to me once: that AWS is allowed to return 500 codes some fixed % of the time, as per their API spec.   I'm not sure if this is that.

**Comment by allisonkarlitskaya** [comment]
er.  @croissanne now, apparently.

**Comment by allisonkarlitskaya** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/s3-resolve-503-slowdown-throttling/

Resolution

> When you receive a 503 SlowDown error, retry the request that caused it. The AWS CLI and SDKs have built-in retry logic and automatically retry 503 SlowDown errors. For more information, see [AWS CLI retries](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html) or [Retry behavior](https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html) from the AWS SDKs and Tools reference guide. You can also control retry behavior with an application or script from the AWS SDKs. For a Python example, see [Defining a retry configuration in a Config object for your Boto3 client](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html#defining-a-retry-configuration-in-a-config-object-for-your-boto3-client) in the Boto3 documentation.

> 503 SlowDown errors can also be caused by two or more simultaneous PUT calls on the same object key due to Amazon S3 [Strong Consistency](https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/). When a PUT request is made in Amazon S3, Amazon S3 automatically stores your object redundantly across multiple Availability Zones. This process may take up to several hundred milliseconds. To avoid seeing 503 SlowDown errors, allow time between PUT requests to the same object key.

**Comment by martinpitt** [comment]
This is not really AWS, is it? This is going to Linode. But may be the same implementation, of course. Thank you!
