### ISSUE TITLE
Refresh arch image, for stratis 3.5

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#4967]
* [ ] FAIL: image-refresh arch

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20230705-071313.log

**Comment by allisonkarlitskaya** [comment]
Let's see how #4968 goes.

**Comment by allisonkarlitskaya** [comment]
#4968 successfully refreshed and is running gating tests now, so let's close this.
