### ISSUE TITLE
Nightly tests did not succeed on fedora-rawhide-boot

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/bots#5344]
Tests failed on 9d90f5f9be606a94b89dc21971c31ef770315a8c

**Comment by allisonkarlitskaya** [comment]
That's probably https://github.com/cockpit-project/bots/pull/5343#issuecomment-1747066464

**Comment by jelly** [comment]
Yup, but more importantly it should not happen :)

**Comment by martinpitt** [comment]
Handling in #5343
