### ISSUE TITLE
job-runner: consider fallback to user's github token and s3 keys

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/bots#6030]
> That feels redundant. job-runner itself should just default to ${COCKPIT_GITHUB_TOKEN_FILE:-~/.config/cockpit-dev/github-token}, in other words, use the task.github API. And the spawned temp containers would use container.secrets.github-token. Why is this needed here again?

This is worth discussing, at least as a fallback.  Ditto for S3 keys.  Let's keep that in mind for a follow-up.

**Comment by martinpitt** [comment]
My worry is more that the intended mode of operation requires duplicating my github token, it has to be both in ~/.config and in that toml. That makes rotating tokens harder, and I like "single source of truth". Of course that philosophically collides with your goal of "I want to regularly use a different github token for job-runner than for e.g. tests-trigger". I'm sure you have your reasons, though :grin:

**Comment by allisonkarlitskaya** [comment]
I feel like the `[{file=...}]` notation that got added is a good compromise on this one.
