### ISSUE TITLE
Image refresh for fedora-rawhide

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/bots#6081]
Image refresh for fedora-rawhide
 * [ ] FAIL: image-refresh fedora-rawhide

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-a9b41af3-20240313-122947/log.html

**Comment by martinpitt** [comment]
Uh, I can reproduce this locally, the .bootstrap script apparently needs adjustment. They may have changed the image build process.
