### ISSUE TITLE
logind takes a while to update utmp

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#6384]
https://artifacts.dev.testing-farm.io/67ee8504-29c3-4c4e-ad3a-66d686d4d475/

Downstream report: https://github.com/systemd/systemd/issues/32845

**Comment by jelly** [comment]
This should be resolved now with the switch to using the logind api https://github.com/cockpit-project/cockpit/pull/20498

**Comment by martinpitt** [comment]
@jelly Hmm, why? That PR changed the Accounts page, but the test failure is polling `loginctl user-status` (or similar).

**Comment by jelly** [comment]
@martinpitt right, that was fixed in https://github.com/cockpit-project/cockpit/pull/20400 

The link still includes the TestAccounts page issue:
```
# Result testUserPasswords (__main__.TestAccounts.testUserPasswords) failed
# 1 TEST FAILED [90s on d0958865d03f]
not ok 54 test/verify/check-users TestAccounts.testUserPasswords [ND@-1] # RETRY 1 (be robust against unstable tests)
```

Which was fixed by https://github.com/cockpit-project/cockpit/pull/20498

**Comment by martinpitt** [comment]
@jelly Our automatic cleanup actually noticed that now, see PR #6538 :tada:
