### ISSUE TITLE
coreutils no longer lists web logins in `who`

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/bots#6789]
Rough outline of what happened:

 - coreutils-9.5-8.fc41 added systemd-devel to its build dependencies
 - this switched on a code path in gnulib which sources "current users" data from logind, but excludes sessions that have neither a tty or a seat and define their session type as something other than "tty" (we use "web").
 - as a result, we no longer get listed in `who` output on Fedora 41 (although somewhat likely to spread in the future, as this is an upstream issue)

Upstream: https://lists.gnu.org/archive/html/bug-gnulib/2024-08/msg00160.html
Downstream: https://bugzilla.redhat.com/show_bug.cgi?id=2307847

**Comment by allisonkarlitskaya** [comment]
Here's the email that I sent to bug-gnulib.  I'm starting to think that this may never appear on the archive, so I'll include it here.  I have no idea what else I should do.

> To: bug-gnulib@gnu.org
> Subject: tty heuristics in lib/readutmp.c exclude "web" sessions
> 
> Fedora recently added systemd-devel to the build dependencies for coreutils:
>  - https://src.fedoraproject.org/rpms/coreutils/c/d3137f0cd04f6c716ef7c64ae35aa653e22aefea?branch=f41
> 
> This had the side-effect of the ./configure script defining READUTMP_USE_SYSTEMD, enabling read_utmp_from_systemd() in lib/readutmp.c:
>  - http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/readutmp.c;h=10d79d1d81a5eeb9da7cbfcc72f214430abcfa2c;hb=HEAD#l800
> 
> This impacts the output of the "who" command when someone is logged in via Cockpit.  The old version printed:
> 
>     admin    web console  2024-08-26 08:46 (::ffff:172.27.0.2)
> 
> and the new version simply doesn't list the login.
> 
> The readutmp code generally only lists a session if it either has a tty defined or if it has an associated seat.  Not all login session are like that.  Consider a command run over ssh without allocating a terminal.  In that case though, there is a heuristic (search "Try harder" in the code) that gets enabled if the session type (as returned by sd_session_get_type()) is set to "tty" (which it is for ssh, even if there is no actual pseudoterminal device).  That heuristic results in the name of the service being written in place of the tty device.
> 
> Cockpit sets its session type to "web" and therefore doesn't get the same treatment.  "web" is a supported session type in systemd-logind since ~10 years, although it was never documented.  See https://github.com/systemd/systemd/pull/34128 about that.
> 
> So I guess my wish here is open-ended, but something like "please allow for a way to ensure that web logins appear in the output of who" without requiring us to set our session type to "tty" (which we don't want to do).  This could look like adding a special case for "web" session types but probably a more permissive approach for listing the service name for all sessions without a tty might make sense?  We're also open to setting other session attributes as may be appropriate.  In the utmp case we have some rather old code for writing "web console" as "tty" field, but I'd like to avoid that on the new code path...
> 
> Thanks for your consideration.
> 
> Allison Karlitskaya

**Comment by cockpituous** [comment]
fedora-41
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestLogin.testBasic)
Starting ChromeDriver 127.0.6533.99 (f31af5097d90ef5ae5bd7b8700199bc6189ba34d-refs/branch-heads/6533@{#1910}) on port 59181
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
useradd: failed to reset the lastlog entry of UID 1003: No such file or directory
Creating mailbox file: File exists
> info: Authentication failed
> info: Authentication failed
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-static-login", line 122, in testBasic
    self.assertRegex(m.execute("who"), r"(^|\n)admin *web.*(\d+\.\d+|::)")
AssertionError: Regex didn't match: '(^|\\n)admin *web.*(\\d+\\.\\d+|::)' not found in 'root     sshd         2024-08-26 10:10 (172.27.0.2)\n'

Wrote screenshot to TestLogin-testBasic-fedora-41-127.0.0.2-2701-FAIL.png
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
Wrote HTML dump to TestLogin-testBasic-fedora-41-127.0.0.2-2701-FAIL.html
Wrote JS log to TestLogin-testBasic-fedora-41-127.0.0.2-2701-FAIL.js.log
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Journal extracted to TestLogin-testBasic-fedora-41-127.0.0.2-2701-FAIL.log.gz
> warn: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warn: cockpit.format_{bytes,bits}[_per_sec](..., GiB, [object Object]) is deprecated.
> warn: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-static-login", line 122, in testBasic
    self.assertRegex(m.execute("who"), r"(^|\n)admin *web.*(\d+\.\d+|::)")
AssertionError: Regex didn't match: '(^|\\n)admin *web.*(\\d+\\.\\d+|::)' not found in 'root     sshd         2024-08-26 10:10 (172.27.0.2)\n'

# Result testBasic (__main__.TestLogin.testBasic) failed
# 1 TEST FAILED [15s on 3fe644dbd323]
not ok 62 test/verify/check-static-login TestLogin.testBasic [ND@4]
```
First occurrence: 2024-08-26T10:10:18.812969+00:00 | revision ab78a2e9739f0b07961ef677c4cb838af7691f7b
Times recorded: 1
Latest occurrences:

- 2024-08-26T10:10:18.812969+00:00 | revision ab78a2e9739f0b07961ef677c4cb838af7691f7b
