### ISSUE TITLE
ssh - listener socket -  too long name  for Unix domain socket

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/bots#6806]
Hi,
I've tested the cockpit with some machine with long hostname and I've met the issue 
```
17:35:47                 out: # testBasic (__main__.TestApps.testBasic)
17:35:47                 out: Starting machine1 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.example.com-22
17:35:47                 out: Assuming machine is already running
17:35:47                 out: + ! test -f /run/nologin && cat /proc/sys/kernel/random/boot_id
17:35:48                 out: unix_listener: path "/tmp/.cockpit-test-resources/ssh-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.example.com-22-root-1757212.f7IbxcOE2AKZBgW6" too long for Unix domain socket
17:35:48                 out: ssh: connection refused, trying again
```
seems We've met the issue: 
https://stackoverflow.com/questions/35970686/ansible-ssh-error-unix-listener-too-long-for-unix-domain-socket

We should probably use `%C` in ssh config, to avoid to exceed this control path file name or maybe possible to use some cmd line option and use own customized path without hostname inside path: 
```
Host *
  ControlPath ~/.ssh/control/%C
  ControlMaster auto
```

Thanks&Regards
Honza

**Comment by martinpitt** [comment]
Indeed I figure the reason is the excessively long host name. Unix socket paths are limited to something like 118 characters or so
