### ISSUE TITLE
queue crash: BrokenPipeError in publish-wrapper on a collision

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#697]
```
checked out bots/ ref d0085bf225409e17ac8262adf7c0ea2d087cf13c
Expected {"context": "continuous-atomic@cockpit-project/cockpit/rhel-7.8", "description": "Testing in progress [3-cockpit-9]", "target_url": "https://logs.cockpit-project.org/logs/pull-694-20200328-211329-d0085bf2
State not as expected. Possible collision. Aborting.
Traceback (most recent call last):
File "./publish-wrapper", line 199, in <module>
sys.exit(main())
File "./publish-wrapper", line 51, in main
ret = task.run(opts)
File "./publish-wrapper", line 193, in run
ret = self.stop_publishing(ret)
File "./publish-wrapper", line 162, in stop_publishing
self.sink.flush()
File "/build/cockpit-project/bots/task/sink.py", line 88, in flush
self.ssh.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe
ERROR:root:./publish-wrapper --repo cockpit-project/bots --test-name pull-694-20200328-211329 --github-context continuous-atomic@cockpit-project/cockpit/rhel-7.8 --revision d0085bf225409e17ac8262adf7c0ea2d087cf13c
```

I've seen these on two other bots within the last 24 hours.

**Comment by martinpitt** [comment]
Idea:
 - change sink to exit with a more distinctive exit code than 1 when it detects a collision
 - change sink/sink.py 's flush() method to see if the ssh process already exited, and cleanly exit when it did with that magic exit code, otherwise throw an error.

**Comment by martinpitt** [comment]
I can reproduce the crash locally by abusing PR #699 for a bit, and hacking my local ~/sink:

```diff
--- sink/sink
+++ sink/sink
@@ -205,7 +205,7 @@ class GitHub(object):
             if self.child == 0:
                 ret = 0
                 try:
-                    if not self.watches(token, watches):
+                    if True or not self.watches(token, watches):
                         os.kill(os.getppid(), signal.SIGTERM)
                         stderr.write(b"State not as expected. Possible collision. Aborting.\n")
                         stderr.flush()
```

```
TEST_PUBLISH=localhost ./publish-wrapper --repo cockpit-project/bots --test-name pull-699-testcrash --github-context fedora-32@cockpit-project/cockpit-podman --revision 54c609863c3a110bdad7d1c167c20f685cab11d0 "echo hello; sleep 10"
```

I tried to fix it with [this commit](https://github.com/martinpitt/bots/commit/fd27f3784eb309b2e0fa0cd2084558150009c0e2), but that doesn't help: Unfortunately attempting to intercept ssh exiting early shows that ssh exits with 255, i. e. a generic ssh  connection error, instead of 77. That is a bit awkward, as we don't want to generally ignore that error.  That watches code in the sink is rather hard to understand. It's also buggy as it blindly intercepts all exceptions and exits with 0 on them. This needs some more work..

**Comment by Gundersanne** [comment]
So I experimented a bit with this, and I found that that if you kill the ppid (the parent being the command that's suplied to ssh) as a child process with `signal.SIGTERM`, ssh will exit 255. `signal.SIGINT` for instance will result in exit 1.

You can't really set the ssh exit code from the forked/child process, only from the parent. So a slightly more complex solution is needed here. Ideally I'd like to get rid of os.fork here because it makes code so difficult to read imo.

**Comment by martinpitt** [comment]
Thanks @Gundersanne! If we can get rid of the fork, that'd be nice of course -- I don't really understand all the watch stuff, I'm afraid.

But one idea: The child could SIGUSR1 its parent, and the parent installs an USR1 signal handler which exits with 77?

**Comment by Gundersanne** [comment]
https://github.com/cockpit-project/cockpituous/pull/337

and 

https://github.com/cockpit-project/bots/pull/1141

**Comment by martinpitt** [comment]
Nice, thanks @Gundersanne ! Closing until we see this again.
