### ISSUE TITLE
Comment links to 404

### ISSUE THREAD

**Issue by massey101** [cockpit-project/bots#888]
Just a small one. I was wondering why we were stopping rhsmcertd here but the link 404's.

Does anyone remember what it was? There's a time travel wall in the git blame.

```python
        # HACK: https://github.com/candlepin/subscription-manager/issues/1404
        subprocess.call(["systemctl", "disable", "rhsmcertd"])
        subprocess.call(["systemctl", "stop", "rhsmcertd"])
```

**Comment by marusak** [comment]
:man_shrugging: but it is in install script so we can try to just drop it and run tests to see how it handles.

btw. it was introduced in https://github.com/cockpit-project/cockpit/commit/03e38c042e30f3d7adcd7039db944041db3f207e
